var rawImageAssets = {
  "clear-100x50.png": "assets/clear-100x50.png"
, "green-100x50.png": "assets/green-100x50.png"
, "blue.png": "assets/blue.png"
, "ggrr-256x256.png": "assets/ggrr-256x256.png"
, "rrgg-256x256.png": "assets/rrgg-256x256.png"
, "4x2.png": "assets/4x2.png"
, "green-16x16.png": "assets/green-16x16.png"
, "red-16x16.png": "assets/red-16x16.png"
, "broken.png": "assets/broken.png"
, "green-100x50.png": "assets/green-100x50.png"
, "transparent.png": "assets/transparent.png"
, "2x2.png": "assets/2x2.png"
, "blue-area.png": "assets/blue-area.png"
, "yellow75.png": "assets/yellow75.png"
, "green-1x1.png": "assets/green-1x1.png"
, "movie_300_frame_0.png": "assets/movie_300_frame_0.png"
, "blue-border.png": "assets/blue-border.png"
, "red.png": "assets/red.png"
, "blue96x96.png": "assets/blue96x96.png"
, "green-256x256.png": "assets/green-256x256.png"
, "background.png": "assets/background.png"
, "transparent50.png": "assets/transparent50.png"
, "clear-100x50.png": "assets/clear-100x50.png"
, "smiley.png": "assets/smiley.png"
, "threecolors.png": "assets/threecolors.png"
, "green-2x2.png": "assets/green-2x2.png"
, "yellow.png": "assets/yellow.png"
, "redtransparent.png": "assets/redtransparent.png"
, "pattern.png": "assets/pattern.png"
, "grgr-256x256.png": "assets/grgr-256x256.png"
, "black-rectangle.png": "assets/black-rectangle.png"
, "anim-poster-gr.png": "assets/anim-poster-gr.png"
, "anim-gr.png": "assets/anim-gr.png"
, "fail.gif": "assets/fail.gif"
, "rgrg-256x256.png": "assets/rgrg-256x256.png"
, "anim-gr.gif": "assets/anim-gr.gif"
, "apng.png": "assets/apng.png"
, "canvas-line.png": "assets/canvas-line.png"
, "2x4.png": "assets/2x4.png"
, "green.png": "assets/green.png"

}
